name: Benchmark PR

on:
  pull_request_target:
    types: [labeled]

jobs:
  benchmark:
    if: ${{ github.event.label.name == 'benchmark' }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
    outputs:
      PR-BENCH: ${{ steps.benchmark-pr.outputs.BENCH_RESULT }}
      DEFAULT-BENCH: ${{ steps.benchmark-default.outputs.BENCH_RESULT }}
    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false
          ref: ${{github.event.pull_request.head.sha}}
          repository: ${{github.event.pull_request.head.repo.full_name}}

      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install
        run: |
          npm install --ignore-scripts

      - name: Run benchmark
        id: benchmark-pr
        run: |
          echo 'BENCH_RESULT<<EOF' >> $GITHUB_OUTPUT
          npm run --silent bench >> $GITHUB_OUTPUT
          echo 'EOF' >> $GITHUB_OUTPUT

      # master benchmark
      - uses: actions/checkout@v3
        with:
          ref: refs/heads/${{ github.event.repository.default_branch }}

      - name: Install
        run: |
          npm install --ignore-scripts

      - name: Run benchmark
        id: benchmark-default
        run: |
          echo 'BENCH_RESULT<<EOF' >> $GITHUB_OUTPUT
          npm run --silent bench >> $GITHUB_OUTPUT
          echo 'EOF' >> $GITHUB_OUTPUT

  output-benchmark:
    needs: 
      - benchmark
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Comment PR
        uses: thollander/actions-comment-pull-request@v2
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          message: |
            **PR**:
            ```
            ${{ needs.benchmark.outputs.PR-BENCH }}
            ```
            **${{ github.event.repository.default_branch }}**:
            ```
            ${{ needs.benchmark.outputs.DEFAULT-BENCH }}
            ```

  remove-label:
    if: "always()"
    needs: 
      - benchmark
      - output-benchmark
    runs-on: ubuntu-latest
    steps:
      - name: Remove benchmark label
        uses: octokit/request-action@v2.x
        id: remove-label
        with:
          route: DELETE /repos/{repo}/issues/{issue_number}/labels/{name}
          repo: ${{ github.event.pull_request.head.repo.full_name }}
          issue_number: ${{ github.event.pull_request.number }}
          name: benchmark
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
